### ISSUE TITLE
HUD not show speed and colors (CS:GO)

### ISSUE THREAD

**Issue by wer1Kua** [shavitush/bhoptimer#120]
Wath screens: [http://imgur.com/a/38P7P](http://imgur.com/a/38P7P)

**Comment by Technoblazed** [comment]
Are you using the latest source code?

**Comment by shavitush** [comment]
for some reason it detects your server as a CS:S server instead of a CS:GO server. is you server non-steam?

**Comment by wer1Kua** [comment]
> Are you using the latest source code?
Yes, I'm using latest source code from github.

> for some reason it detects your server as a CS:S server instead of a CS:GO server. is you server non-steam?
No, It's legacy Steam Dedicated Server.

**Comment by shavitush** [comment]
Someone else reported the same issue. AFAIK it's a SourceMod issue and nothing caused by the plugin. A quick workaround would be to recompile with this line edited in `shavit-core`:

> EngineVersion evType = GetEngineVersion();

Edited to

> EngineVersion evType = Game_CSGO;

**Comment by wer1Kua** [comment]
This is not work.

**Comment by shavitush** [comment]
I'm looking at [your fork](https://github.com/wer1Kua/bhoptimer) and it is.. very far behind the current state of my bhoptimer.

**Comment by wer1Kua** [comment]
I'm don't using my fork now, I'm using your latest source code.

**Comment by shavitush** [comment]
In `shavit-hud`, change line 406 from:
```
if(gSG_Type == Game_CSGO)
```
to
```
if(GetEngineVersion() == Engine_CSGO)
```

Let me know if it solves your problem.

**Comment by wer1Kua** [comment]
Yeah, problem is solved!

**Comment by wer1Kua** [comment]
But wait, my CS:GO crash is I'm trying set Start Zone.

**Comment by shavitush** [comment]
i think you forgot to add the materials/ folder i added to both your server and fastdl
