### ISSUE TITLE
Booster abuse with checkpoints

### ISSUE THREAD

**Issue by mariokeks** [shavitush/bhoptimer#1237]
Maps having triggers with outputs such as:
`"OnStartTouch" "!activator,AddOutput,basevelocity 0 150 0,0,-1"`
can be abused in segmented styles or practise 

An easy example of this is on **bhop_challenjour_v2** 
```
"model" "*179"
"wait" "0.1"
"StartDisabled" "0"
"spawnflags" "4097"
"origin" "14795 5049 12728"
"classname" "trigger_multiple"
"hammerid" "298112"
"OnStartTouch" "!activator,AddOutput,basevelocity 0 150 0,0,-1"
```
Saving within this trigger and teleporting to it will just add the boost again every time you save and teleport.
This also happens when the timer restores the stats when joining back into a team (shavit_checkpoints_restorestates)

**Comment by rtldg** [comment]
This is fixed by eventqueuefix.
For Windows, you'll also need [eventqueuefixfix](https://github.com/srcwr/eventqueuefixfix) for now (which isn't really linked anywhere yet, sorry).

**Comment by mariokeks** [comment]
This still happens on linux with the latest release of shavit's bhop timer and eventqueuefix

SourceMod 1.12.0.7198, by AlliedModders LLC
Metamod:Source version 1.12.0-dev+12

**Comment by rtldg** [comment]
Okay, I see what you mean. I thought this case was already handled by stripping events on teleport, but I guess only for !restart.
A proper fix would probably involved saving/reloading some of the entity touched-list stuff but it'd be a bit complicated afair (esp. if we want to preserve it in checkpoints/save-states across map changes/reloads).

**Comment by rtldg** [comment]
I don't have a fix in mind for this right now, so this will probably sit for a while.
I reckon the touched-list saving/reloading thing would be good to investigate.
