### ISSUE TITLE
No maptiers table D:

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#153]
L 08/07/2016 - 19:38:31: [shavit-rankings.smx] Timer (rankings module) error! Set tier cache failed. Reason: no such table: maptiers

Also, are tiers meant to display as x.0 ?

**Comment by shavitush** [comment]
you can set map tiers to 5.4 for example, so yes

**Comment by Technoblazed** [comment]
cool np

**Comment by shavitush** [comment]
fixed but forgot to reference issue

**Comment by Technoblazed** [comment]
Still isn't fixed using the latest code, even with the cvar set to 1, it still inserts into the sqlite db.

**Comment by shavitush** [comment]
fml

**Comment by shavitush** [comment]
does it fix with this part removed?

![atom_2016-08-08_16-39-52](https://cloud.githubusercontent.com/assets/3672466/17481612/c315e516-5d86-11e6-8789-4761ba35cae4.png)

**Comment by Technoblazed** [comment]
nope, still doesnt work

**Comment by shavitush** [comment]
will be fixed within #154
