### ISSUE TITLE
Does not work shavit_core_blockleftright 1

### ISSUE THREAD

**Issue by Lime18** [shavitush/bhoptimer#405]
While I use this option https://forums.alliedmods.net/showpost.php?p=1615070&postcount=13

**Comment by strafe** [comment]
Why would you use both `shavit_core_blockleftright` and the other plugin?

**Comment by Lime18** [comment]
Since shavit_core_blockleftright 1 does not block + left / right

**Comment by shavitush** [comment]
Not a bug. Enable `block_pleft` and `block_pright` in `shavit-styles.cfg`.

It's like that because autobhop speedruns may require +left/right as they're done at lower sensitives (real world examples: bhop_challenjour's last stage and bhop_aux's hole stage). However, +left/right may be abused for long jump scripts in kz_bhop maps. So the scroll styles have it enabled by default

**Comment by strafe** [comment]
@shavitush what is the purpose of that cvar then?

**Comment by shavitush** [comment]
Those settings require the convar.
You could make map configs where this isn't enabled.
For example maps/cfg/bhop_badges.cfg will have it enabled, or maps/cfg/bhop_badges2.cfg where it's disabled.

**Comment by strafe** [comment]
But it says in the style config `doesn't take effect with shavit_core_blockleftright 1`, implying that if you are using `shavit_core_blockleftright 1` they will do nothing?

**Comment by shavitush** [comment]
The comment is wrong. I fixed it a few hours ago, see b15ec4e8ccfaa1780ff184aeb8e4a5858d8de64e.

**Comment by Lime18** [comment]
@shavitush, thanks, I understood where to look.
		"block_pleft"		"0" // block +left (doesn't take effect with shavit_core_blockleftright 1)
		"block_pright"		"0" // block +left (doesn't take effect with shavit_core_blockleftright 1)
		"block_pstrafe"	"0" // stops timer on +strafe usage

**Comment by Lime18** [comment]
They go ... @strafe said true, with shavit_core_blockleftright 1 it still does not block.

**Comment by shavitush** [comment]
On scroll:
> 「bhop」» You have selected to play Scroll.
> 「bhop」» Timer stopped! Detected +left/right on a disallowed style.

On autobhop styles:
> 「bhop」» You have selected to play Normal.

Normal config:
```
"block_pleft"		"0"
"block_pright"		"0"
```

Scroll config:
```
"block_pleft"		"1"
"block_pright"		"1"
```

**Comment by strafe** [comment]
Little bit confusing, blacky's newer timer stops you from using both commands in the same jump which seems simpler and still effective against lj scripts/cheats.

**Comment by shavitush** [comment]
If anything, adding more and more things to cache makes it more complicated rather than simpler :/.
